[phases.setup]
nixPkgs = ["nodejs_18", "yarn-1_x"]

[phases.install]
cmds = ["yarn install --frozen-lockfile", "cd server && npm install --include=dev"]

[phases.build]
cmds = ["cd server && npm run build"]

[start]
cmd = "npm start"
